### ISSUE TITLE
Can't create matrix design more then 40 000 shapes

### ISSUE THREAD

**Issue by SunnyBerlin** [mm-project/qt_painter#209]
When trying to create matrix design RQ wont allow to create more then 200 by 200 ( ~40k shapes )
<img width="596" alt="image" src="https://github.com/mm-project/qt_painter/assets/127693048/5c6cf4cc-f594-4606-b4a8-25d4e92e5928">

**to reproduce by unit-test**

```
#include "../RegionQueryService.hpp"

#include <QPoint>

#include <cassert>
#include <iostream>


template <typename T> IShapePtr create(QPoint p1, QPoint p2)
{
    IShapePtr shape = std::shared_ptr<T>(new T);
    shape->addPoint(p2);
    shape->addPoint(p1);

    return shape;
}

void create_rect(int x1, int y1, int x2, int y2)
{
    RegionQuery &rq = RegionQuery::getInstance();
    rq.insertObject(create<Rectangle>(QPoint(x1, y1), QPoint(x2, y2)));
}


void create_rect_at_given_cell_and_row(int column, int row)
{
    int delta = 100;
    int epsilon = 90;
    create_rect(delta*row,delta*column,delta*row-epsilon,delta*column-epsilon);
}


bool test_rq_by_inserting_1k_by_1k_objs()
{

    for(int column=0; column<1000; column++)
        for(int row=0; row<1000; row++)
            create_rect_at_given_cell_and_row(column,row);
}


int main(int argc, char **argv)
{
    test_rq_by_inserting_1k_by_1k_objs();
    std::cout << "pass" << std::endl;
}
```

./etc/bsys/bin/makeUnitTests.sh
./sqa/bin/runUnitTests.sh

*Stack dump*
```
#0  0x00007ffff6fa3e6e in _int_malloc (av=av@entry=0x7ffff7119c80 <main_arena>, bytes=bytes@entry=24)
    at ./malloc/malloc.c:3903
#1  0x00007ffff6fa52e2 in __GI___libc_malloc (bytes=24) at ./malloc/malloc.c:3321
#2  0x00007ffff71f69cc in operator new(unsigned long) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x0000555555582168 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<rq::CNode<IShape>*> (
    this=0x7fffff7ff198, __p=0x5555562cda10) at /usr/include/c++/11/bits/shared_ptr_base.h:596
#4  0x0000555555581889 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<rq::CNode<IShape>*> (
    this=0x7fffff7ff198, __p=0x5555562cda10) at /usr/include/c++/11/bits/shared_ptr_base.h:607
#5  0x0000555555580910 in std::__shared_ptr<rq::CNode<IShape>, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<rq::CNode<IShape>, void> (this=0x7fffff7ff190, __p=0x5555562cda10) at /usr/include/c++/11/bits/shared_ptr_base.h:1099
#6  0x000055555557faad in std::shared_ptr<rq::CNode<IShape> >::shared_ptr<rq::CNode<IShape>, void> (
    this=0x7fffff7ff190, __p=0x5555562cda10) at /usr/include/c++/11/bits/shared_ptr.h:160
#7  0x000055555557e176 in rq::RQtree<IShape>::_insert (this=0x5555555b8150,
    root=std::shared_ptr<rq::CNode<IShape>> (empty) = {...},
    point=std::shared_ptr<rq::IRQobject> (use count 2, weak count 0) = {...}, depth=47637)
    at /home/levon/my/qt_painter/src/core/rq/RQtree.hpp:114
#8  0x000055555557e2ec in rq::RQtree<IShape>::_insert (this=0x5555555b8150,
    root=std::shared_ptr<rq::CNode<IShape>> (use count 1, weak count 0) = {...},
    point=std::shared_ptr<rq::IRQobject> (use count 2, weak count 0) = {...}, depth=47636)
    at /home/levon/my/qt_painter/src/core/rq/RQtree.hpp:123
#9  0x000055555557e2ec in rq::RQtree<IShape>::_insert (this=0x5555555b8150,
    root=std::shared_ptr<rq::CNode<IShape>> (use count 1, weak count 0) = {...},
    point=std::shared_ptr<rq::IRQobject> (use count 2, weak count 0) = {...}, depth=47635)
    at /home/levon/my/qt_painter/src/core/rq/RQtree.hpp:123
#10 0x000055555557e2ec in rq::RQtree<IShape>::_insert (this=0x5555555b8150,
    root=std::shared_ptr<rq::CNode<IShape>> (use count 1, weak count 0) = {...},
    point=std::shared_ptr<rq::IRQobject> (use count 2, weak count 0) = {...}, depth=47634)
    at /home/levon/my/qt_painter/src/core/rq/RQtree.hpp:123
#11 0x000055555557e2ec in rq::RQtree<IShape>::_insert (this=0x5555555b8150,
```

**Comment by SunnyBerlin** [comment]
fixed in #220
